// Bun server emulating the OpenAI REST API surface. Every completion's
// content is typed by a human operator at the process's stdin instead of
// being generated by a model.
import { MODELS, MODEL_IDS_SET } from "./models";
import { closeStdinPrompt, promptForCompletion } from "./stdin";

const PORT = Number(process.env.PORT ?? 8787);

interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool" | "developer";
  content: string | Array<{ type: string; text?: string }> | null;
}

interface ChatCompletionRequest {
  model: string;
  messages: ChatMessage[];
  stream?: boolean;
}

interface CompletionRequest {
  model: string;
  prompt: string | string[];
  stream?: boolean;
}

function messageText(content: ChatMessage["content"]): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .map((part) => (typeof part.text === "string" ? part.text : ""))
      .join(" ")
      .trim();
  }
  return "";
}

function lastUserMessageText(messages: ChatMessage[]): string {
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === "user") return messageText(messages[i].content);
  }
  return messages.length > 0 ? messageText(messages[messages.length - 1].content) : "";
}

// OpenAI's real usage counts are token counts; this is a cheap proxy so
// numbers stay internally consistent (whitespace-delimited word count).
function estimateTokens(text: string): number {
  const trimmed = text.trim();
  return trimmed.length === 0 ? 0 : trimmed.split(/\s+/).length;
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function errorResponse(message: string, status: number, type = "invalid_request_error"): Response {
  return jsonResponse({ error: { message, type, param: null, code: null } }, status);
}

function requireKnownModel(model: unknown): string | Response {
  if (typeof model !== "string" || model.length === 0) {
    return errorResponse("you must provide a model parameter", 400);
  }
  if (!MODEL_IDS_SET.has(model)) {
    return errorResponse(
      `The model '${model}' does not exist. Known models: ${[...MODEL_IDS_SET].join(", ")}`,
      404,
      "invalid_request_error",
    );
  }
  return model;
}

function sseChunkStream(chunks: unknown[]): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  return new ReadableStream({
    async start(controller) {
      for (const chunk of chunks) {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(chunk)}\n\n`));
        await new Promise((resolve) => setTimeout(resolve, 15));
      }
      controller.enqueue(encoder.encode("data: [DONE]\n\n"));
      controller.close();
    },
  });
}

function sseResponse(chunks: unknown[]): Response {
  return new Response(sseChunkStream(chunks), {
    headers: {
      "content-type": "text/event-stream",
      "cache-control": "no-cache",
      connection: "keep-alive",
    },
  });
}

async function handleChatCompletions(req: Request): Promise<Response> {
  let body: ChatCompletionRequest;
  try {
    body = (await req.json()) as ChatCompletionRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  if (!Array.isArray(body.messages) || body.messages.length === 0) {
    return errorResponse("'messages' is required and must be a non-empty array", 400);
  }

  const replyText = await promptForCompletion({
    model: modelCheck,
    endpoint: "chat.completions",
    lastUserMessage: lastUserMessageText(body.messages),
  });

  const id = `chatcmpl-${crypto.randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  const promptTokens = body.messages.reduce((sum, m) => sum + estimateTokens(messageText(m.content)), 0);
  const completionTokens = estimateTokens(replyText);

  if (body.stream) {
    const roleChunk = {
      id,
      object: "chat.completion.chunk",
      created,
      model: modelCheck,
      choices: [{ index: 0, delta: { role: "assistant" }, finish_reason: null }],
    };
    const words = replyText.length === 0 ? [] : replyText.split(/(?<=\s)/);
    const contentChunks = words.map((word) => ({
      id,
      object: "chat.completion.chunk",
      created,
      model: modelCheck,
      choices: [{ index: 0, delta: { content: word }, finish_reason: null }],
    }));
    const finalChunk = {
      id,
      object: "chat.completion.chunk",
      created,
      model: modelCheck,
      choices: [{ index: 0, delta: {}, finish_reason: "stop" }],
    };
    return sseResponse([roleChunk, ...contentChunks, finalChunk]);
  }

  return jsonResponse({
    id,
    object: "chat.completion",
    created,
    model: modelCheck,
    choices: [
      {
        index: 0,
        message: { role: "assistant", content: replyText },
        logprobs: null,
        finish_reason: "stop",
      },
    ],
    usage: {
      prompt_tokens: promptTokens,
      completion_tokens: completionTokens,
      total_tokens: promptTokens + completionTokens,
    },
  });
}

async function handleCompletions(req: Request): Promise<Response> {
  let body: CompletionRequest;
  try {
    body = (await req.json()) as CompletionRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  const promptText = Array.isArray(body.prompt) ? body.prompt.join("\n") : (body.prompt ?? "");

  const replyText = await promptForCompletion({
    model: modelCheck,
    endpoint: "completions",
    lastUserMessage: promptText,
  });

  const id = `cmpl-${crypto.randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  const promptTokens = estimateTokens(promptText);
  const completionTokens = estimateTokens(replyText);

  if (body.stream) {
    const words = replyText.length === 0 ? [] : replyText.split(/(?<=\s)/);
    const contentChunks = words.map((word) => ({
      id,
      object: "text_completion",
      created,
      model: modelCheck,
      choices: [{ text: word, index: 0, logprobs: null, finish_reason: null }],
    }));
    const finalChunk = {
      id,
      object: "text_completion",
      created,
      model: modelCheck,
      choices: [{ text: "", index: 0, logprobs: null, finish_reason: "stop" }],
    };
    return sseResponse([...contentChunks, finalChunk]);
  }

  return jsonResponse({
    id,
    object: "text_completion",
    created,
    model: modelCheck,
    choices: [{ text: replyText, index: 0, logprobs: null, finish_reason: "stop" }],
    usage: {
      prompt_tokens: promptTokens,
      completion_tokens: completionTokens,
      total_tokens: promptTokens + completionTokens,
    },
  });
}

interface EmbeddingsRequest {
  model: string;
  input: string | string[];
}

// Deterministic pseudo-random vector seeded from the input text — no stdin
// prompt here since typing floating-point vectors by hand isn't practical.
function fakeEmbedding(text: string, dims = 32): number[] {
  let seed = 0;
  for (let i = 0; i < text.length; i++) seed = (seed * 31 + text.charCodeAt(i)) >>> 0;
  const vec: number[] = [];
  for (let i = 0; i < dims; i++) {
    seed = (seed * 1103515245 + 12345) >>> 0;
    vec.push((seed / 0xffffffff) * 2 - 1);
  }
  return vec;
}

async function handleEmbeddings(req: Request): Promise<Response> {
  let body: EmbeddingsRequest;
  try {
    body = (await req.json()) as EmbeddingsRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  const inputs = Array.isArray(body.input) ? body.input : [body.input];

  return jsonResponse({
    object: "list",
    data: inputs.map((text, index) => ({
      object: "embedding",
      index,
      embedding: fakeEmbedding(String(text)),
    })),
    model: modelCheck,
    usage: {
      prompt_tokens: inputs.reduce((sum, t) => sum + estimateTokens(String(t)), 0),
      total_tokens: inputs.reduce((sum, t) => sum + estimateTokens(String(t)), 0),
    },
  });
}

function handleModelsList(): Response {
  return jsonResponse({ object: "list", data: MODELS });
}

function handleModelRetrieve(modelId: string): Response {
  const model = MODELS.find((m) => m.id === modelId);
  if (!model) return errorResponse(`The model '${modelId}' does not exist`, 404);
  return jsonResponse(model);
}

const server = Bun.serve({
  port: PORT,
  idleTimeout: 0,
  async fetch(req) {
    const url = new URL(req.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";

    if (req.method === "GET" && path === "/v1/models") return handleModelsList();
    if (req.method === "GET" && path.startsWith("/v1/models/")) {
      return handleModelRetrieve(decodeURIComponent(path.slice("/v1/models/".length)));
    }
    if (req.method === "POST" && path === "/v1/chat/completions") return handleChatCompletions(req);
    if (req.method === "POST" && path === "/v1/completions") return handleCompletions(req);
    if (req.method === "POST" && path === "/v1/embeddings") return handleEmbeddings(req);
    if (req.method === "GET" && path === "/") {
      return jsonResponse({ status: "ok", message: "openai-madeup-endpoint is running" });
    }

    return errorResponse(`Unknown endpoint: ${req.method} ${path}`, 404, "not_found_error");
  },
});

console.log(`openai-madeup-endpoint listening on http://localhost:${server.port}`);
console.log(`Known models: ${MODELS.map((m) => m.id).join(", ")}`);
console.log("Every completion request will prompt you here for the reply text.\n");

process.on("SIGINT", () => {
  closeStdinPrompt();
  process.exit(0);
});
