// Bun server emulating the OpenAI REST API surface. Every completion's
// content — text, tool calls, and reasoning trace — is supplied by a human
// operator through the browser control panel instead of being generated by
// a model.
import { extractImageUrls } from "./images";
import { MODELS, MODEL_IDS_SET } from "./models";
import { closePanel, PANEL_HTML, panelEventStream, resolvePending, submitPrompt, type OperatorOutcome } from "./panel";
import { normalizeTools, normalizeToolChoice, type NormalizedToolChoice } from "./tools";

const PORT = Number(process.env.PORT ?? 8787);

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

interface ContentPart {
  type?: string;
  text?: string;
  image_url?: string | { url?: string };
}

function messageText(content: string | ContentPart[] | null | undefined): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .map((part) => (typeof part.text === "string" ? part.text : ""))
      .join(" ")
      .trim();
  }
  return "";
}

function summarizeContent(content: string | ContentPart[] | null | undefined): string {
  const text = messageText(content);
  const imageCount = Array.isArray(content) ? extractImageUrls(content).length : 0;
  if (imageCount === 0) return text;
  return `${text}${text ? " " : ""}[${imageCount} image(s)]`;
}

// OpenAI's real usage counts are token counts; this is a cheap proxy so
// numbers stay internally consistent (whitespace-delimited word count).
function estimateTokens(text: string): number {
  const trimmed = text.trim();
  return trimmed.length === 0 ? 0 : trimmed.split(/\s+/).length;
}

function chunkWords(text: string): string[] {
  return text.length === 0 ? [] : text.split(/(?<=\s)/);
}

function chunkString(text: string, size: number): string[] {
  if (text.length === 0) return [""];
  const out: string[] = [];
  for (let i = 0; i < text.length; i += size) out.push(text.slice(i, i + size));
  return out;
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function errorResponse(message: string, status: number, type = "invalid_request_error"): Response {
  return jsonResponse({ error: { message, type, param: null, code: null } }, status);
}

function requireKnownModel(model: unknown): string | Response {
  if (typeof model !== "string" || model.length === 0) {
    return errorResponse("you must provide a model parameter", 400);
  }
  if (!MODEL_IDS_SET.has(model)) {
    return errorResponse(
      `The model '${model}' does not exist. Known models: ${[...MODEL_IDS_SET].join(", ")}`,
      404,
      "invalid_request_error",
    );
  }
  return model;
}

function logUnsupportedTools(unsupported: { rawType: string }[]): void {
  if (unsupported.length === 0) return;
  console.log(
    `(note: ${unsupported.length} non-function tool(s) requested but unsupported here: ${unsupported.map((u) => u.rawType).join(", ")})`,
  );
}

interface SseEvent {
  event?: string;
  data: unknown;
}

function sseChunkStream(events: SseEvent[], terminator: string | null): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  return new ReadableStream({
    async start(controller) {
      for (const evt of events) {
        const eventLine = evt.event ? `event: ${evt.event}\n` : "";
        controller.enqueue(encoder.encode(`${eventLine}data: ${JSON.stringify(evt.data)}\n\n`));
        await new Promise((resolve) => setTimeout(resolve, 15));
      }
      if (terminator !== null) controller.enqueue(encoder.encode(`data: ${terminator}\n\n`));
      controller.close();
    },
  });
}

function sseResponse(events: SseEvent[], terminator: string | null = "[DONE]"): Response {
  return new Response(sseChunkStream(events, terminator), {
    headers: {
      "content-type": "text/event-stream",
      "cache-control": "no-cache",
      connection: "keep-alive",
    },
  });
}

// ---------------------------------------------------------------------------
// Chat Completions — POST /v1/chat/completions
// ---------------------------------------------------------------------------

interface ChatToolCall {
  id: string;
  type: "function";
  function: { name: string; arguments: string };
}

interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool" | "developer";
  content: string | ContentPart[] | null;
  tool_calls?: ChatToolCall[];
  tool_call_id?: string;
  name?: string;
}

interface ChatCompletionRequest {
  model: string;
  messages: ChatMessage[];
  tools?: unknown[];
  tool_choice?: unknown;
  stream?: boolean;
}

function formatChatHistory(messages: ChatMessage[]): string[] {
  return messages.map((m) => {
    if (m.role === "assistant" && m.tool_calls && m.tool_calls.length > 0) {
      const calls = m.tool_calls.map((c) => `${c.function.name}(${c.function.arguments})`).join(", ");
      return `assistant -> tool_calls: ${calls}`;
    }
    if (m.role === "tool") {
      return `tool[${m.tool_call_id ?? "?"}]${m.name ? ` ${m.name}` : ""}: ${summarizeContent(m.content).slice(0, 300)}`;
    }
    return `${m.role}: ${summarizeContent(m.content).slice(0, 300)}`;
  });
}

function buildChatStreamEvents(
  id: string,
  created: number,
  model: string,
  outcome: OperatorOutcome,
  finishReason: string,
): SseEvent[] {
  const base = { id, object: "chat.completion.chunk", created, model };
  const payloads: unknown[] = [{ ...base, choices: [{ index: 0, delta: { role: "assistant" }, finish_reason: null }] }];

  if (outcome.thinking) {
    for (const piece of chunkWords(outcome.thinking)) {
      payloads.push({ ...base, choices: [{ index: 0, delta: { reasoning_content: piece }, finish_reason: null }] });
    }
  }

  if (outcome.kind === "text") {
    for (const piece of chunkWords(outcome.text)) {
      payloads.push({ ...base, choices: [{ index: 0, delta: { content: piece }, finish_reason: null }] });
    }
  } else {
    outcome.calls.forEach((call, index) => {
      payloads.push({
        ...base,
        choices: [
          {
            index: 0,
            delta: { tool_calls: [{ index, id: call.id, type: "function", function: { name: call.name, arguments: "" } }] },
            finish_reason: null,
          },
        ],
      });
      for (const piece of chunkString(call.arguments, 24)) {
        payloads.push({
          ...base,
          choices: [{ index: 0, delta: { tool_calls: [{ index, function: { arguments: piece } }] }, finish_reason: null }],
        });
      }
    });
  }

  payloads.push({ ...base, choices: [{ index: 0, delta: {}, finish_reason: finishReason }] });
  return payloads.map((data) => ({ data }));
}

async function handleChatCompletions(req: Request): Promise<Response> {
  let body: ChatCompletionRequest;
  try {
    body = (await req.json()) as ChatCompletionRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  if (!Array.isArray(body.messages) || body.messages.length === 0) {
    return errorResponse("'messages' is required and must be a non-empty array", 400);
  }

  const { functions, unsupported } = normalizeTools(body.tools);
  const toolChoice: NormalizedToolChoice = normalizeToolChoice(body.tool_choice);
  logUnsupportedTools(unsupported);

  const outcome = await submitPrompt({
    model: modelCheck,
    endpoint: "chat.completions",
    historyLines: formatChatHistory(body.messages),
    images: body.messages.flatMap((m) => extractImageUrls(m.content)),
    tools: functions,
    toolChoice,
  });

  const id = `chatcmpl-${crypto.randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  const promptTokens = body.messages.reduce((sum, m) => sum + estimateTokens(messageText(m.content)), 0);
  const reasoningTokens = estimateTokens(outcome.thinking);
  const replyTokens =
    outcome.kind === "text" ? estimateTokens(outcome.text) : outcome.calls.reduce((sum, c) => sum + estimateTokens(c.arguments), 0);
  const usage = {
    prompt_tokens: promptTokens,
    completion_tokens: replyTokens + reasoningTokens,
    total_tokens: promptTokens + replyTokens + reasoningTokens,
    completion_tokens_details: { reasoning_tokens: reasoningTokens },
  };

  const message: Record<string, unknown> = { role: "assistant" };
  if (outcome.thinking) message.reasoning_content = outcome.thinking;
  let finishReason: string;
  if (outcome.kind === "tool_calls") {
    message.content = null;
    message.tool_calls = outcome.calls.map((c) => ({ id: c.id, type: "function", function: { name: c.name, arguments: c.arguments } }));
    finishReason = "tool_calls";
  } else {
    message.content = outcome.text;
    finishReason = "stop";
  }

  if (body.stream) {
    return sseResponse(buildChatStreamEvents(id, created, modelCheck, outcome, finishReason));
  }

  return jsonResponse({
    id,
    object: "chat.completion",
    created,
    model: modelCheck,
    choices: [{ index: 0, message, logprobs: null, finish_reason: finishReason }],
    usage,
  });
}

// ---------------------------------------------------------------------------
// Legacy Completions — POST /v1/completions (text-only, no tools/vision)
// ---------------------------------------------------------------------------

interface CompletionRequest {
  model: string;
  prompt: string | string[];
  stream?: boolean;
}

async function handleCompletions(req: Request): Promise<Response> {
  let body: CompletionRequest;
  try {
    body = (await req.json()) as CompletionRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  const promptText = Array.isArray(body.prompt) ? body.prompt.join("\n") : (body.prompt ?? "");

  const outcome = await submitPrompt({
    model: modelCheck,
    endpoint: "completions",
    historyLines: [`prompt: ${promptText}`],
    images: [],
    tools: [],
    toolChoice: { kind: "none" },
  });
  const replyText = outcome.kind === "text" ? outcome.text : "";

  const id = `cmpl-${crypto.randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  const promptTokens = estimateTokens(promptText);
  const completionTokens = estimateTokens(replyText);

  if (body.stream) {
    const contentChunks = chunkWords(replyText).map((word) => ({
      id,
      object: "text_completion",
      created,
      model: modelCheck,
      choices: [{ text: word, index: 0, logprobs: null, finish_reason: null }],
    }));
    const finalChunk = {
      id,
      object: "text_completion",
      created,
      model: modelCheck,
      choices: [{ text: "", index: 0, logprobs: null, finish_reason: "stop" }],
    };
    return sseResponse([...contentChunks, finalChunk].map((data) => ({ data })));
  }

  return jsonResponse({
    id,
    object: "text_completion",
    created,
    model: modelCheck,
    choices: [{ text: replyText, index: 0, logprobs: null, finish_reason: "stop" }],
    usage: {
      prompt_tokens: promptTokens,
      completion_tokens: completionTokens,
      total_tokens: promptTokens + completionTokens,
    },
  });
}

// ---------------------------------------------------------------------------
// Responses API — POST /v1/responses (tools, vision, reasoning)
// ---------------------------------------------------------------------------

interface ResponsesInputItem {
  type?: string;
  role?: string;
  content?: string | ContentPart[];
  call_id?: string;
  name?: string;
  arguments?: string;
  output?: string;
}

interface ResponsesRequest {
  model: string;
  input: string | ResponsesInputItem[];
  instructions?: string;
  tools?: unknown[];
  tool_choice?: unknown;
  stream?: boolean;
}

function formatResponsesHistory(input: string | ResponsesInputItem[]): string[] {
  if (typeof input === "string") return [`user: ${input}`];
  return input.map((item) => {
    const type = item.type ?? "message";
    if (type === "function_call") return `assistant -> tool_call: ${item.name}(${item.arguments ?? ""}) [${item.call_id}]`;
    if (type === "function_call_output") return `tool[${item.call_id}]: ${String(item.output ?? "").slice(0, 300)}`;
    return `${item.role ?? "user"}: ${summarizeContent(item.content).slice(0, 300)}`;
  });
}

function collectResponsesImages(input: string | ResponsesInputItem[]): string[] {
  if (typeof input === "string") return [];
  return input.flatMap((item) => extractImageUrls(item.content));
}

function estimateResponsesInputTokens(input: string | ResponsesInputItem[]): number {
  if (typeof input === "string") return estimateTokens(input);
  return input.reduce((sum, item) => {
    if (typeof item.content === "string") return sum + estimateTokens(item.content);
    if (Array.isArray(item.content)) return sum + estimateTokens(messageText(item.content));
    if (typeof item.output === "string") return sum + estimateTokens(item.output);
    if (typeof item.arguments === "string") return sum + estimateTokens(item.arguments);
    return sum;
  }, 0);
}

function buildResponsesStreamEvents(finalResponse: Record<string, unknown>): SseEvent[] {
  const events: SseEvent[] = [
    {
      event: "response.created",
      data: { type: "response.created", response: { ...finalResponse, status: "in_progress", output: [], output_text: "" } },
    },
  ];

  const output = finalResponse.output as Record<string, unknown>[];
  output.forEach((item, outputIndex) => {
    if (item.type === "reasoning") {
      const summary = item.summary as { type: string; text: string }[];
      const text = summary[0]?.text ?? "";
      events.push({
        event: "response.output_item.added",
        data: { type: "response.output_item.added", output_index: outputIndex, item: { ...item, summary: [] } },
      });
      for (const piece of chunkWords(text)) {
        events.push({
          event: "response.reasoning_summary_text.delta",
          data: { type: "response.reasoning_summary_text.delta", item_id: item.id, output_index: outputIndex, summary_index: 0, delta: piece },
        });
      }
      events.push({
        event: "response.reasoning_summary_text.done",
        data: { type: "response.reasoning_summary_text.done", item_id: item.id, output_index: outputIndex, summary_index: 0, text },
      });
      events.push({ event: "response.output_item.done", data: { type: "response.output_item.done", output_index: outputIndex, item } });
    } else if (item.type === "message") {
      const content = item.content as { type: string; text: string }[];
      const text = content[0]?.text ?? "";
      events.push({
        event: "response.output_item.added",
        data: { type: "response.output_item.added", output_index: outputIndex, item: { ...item, status: "in_progress", content: [] } },
      });
      for (const piece of chunkWords(text)) {
        events.push({
          event: "response.output_text.delta",
          data: { type: "response.output_text.delta", item_id: item.id, output_index: outputIndex, content_index: 0, delta: piece },
        });
      }
      events.push({
        event: "response.output_text.done",
        data: { type: "response.output_text.done", item_id: item.id, output_index: outputIndex, content_index: 0, text },
      });
      events.push({ event: "response.output_item.done", data: { type: "response.output_item.done", output_index: outputIndex, item } });
    } else if (item.type === "function_call") {
      const args = String(item.arguments ?? "");
      events.push({
        event: "response.output_item.added",
        data: { type: "response.output_item.added", output_index: outputIndex, item: { ...item, status: "in_progress", arguments: "" } },
      });
      for (const piece of chunkString(args, 24)) {
        events.push({
          event: "response.function_call_arguments.delta",
          data: { type: "response.function_call_arguments.delta", item_id: item.id, output_index: outputIndex, delta: piece },
        });
      }
      events.push({
        event: "response.function_call_arguments.done",
        data: { type: "response.function_call_arguments.done", item_id: item.id, output_index: outputIndex, arguments: args },
      });
      events.push({ event: "response.output_item.done", data: { type: "response.output_item.done", output_index: outputIndex, item } });
    }
  });

  events.push({ event: "response.completed", data: { type: "response.completed", response: finalResponse } });
  return events;
}

async function handleResponses(req: Request): Promise<Response> {
  let body: ResponsesRequest;
  try {
    body = (await req.json()) as ResponsesRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  if (typeof body.input !== "string" && !Array.isArray(body.input)) {
    return errorResponse("'input' is required and must be a string or an array of input items", 400);
  }

  const { functions, unsupported } = normalizeTools(body.tools);
  const toolChoice: NormalizedToolChoice = normalizeToolChoice(body.tool_choice);
  logUnsupportedTools(unsupported);

  const outcome = await submitPrompt({
    model: modelCheck,
    endpoint: "responses",
    historyLines: [...(body.instructions ? [`instructions: ${body.instructions}`] : []), ...formatResponsesHistory(body.input)],
    images: collectResponsesImages(body.input),
    tools: functions,
    toolChoice,
  });

  const id = `resp_${crypto.randomUUID()}`;
  const createdAt = Math.floor(Date.now() / 1000);
  const inputTokens = estimateResponsesInputTokens(body.input) + estimateTokens(body.instructions ?? "");
  const reasoningTokens = estimateTokens(outcome.thinking);
  const replyTokens =
    outcome.kind === "text" ? estimateTokens(outcome.text) : outcome.calls.reduce((sum, c) => sum + estimateTokens(c.arguments), 0);
  const outputTokens = replyTokens + reasoningTokens;

  const output: Record<string, unknown>[] = [];
  if (outcome.thinking) {
    output.push({
      id: `rs_${crypto.randomUUID()}`,
      type: "reasoning",
      summary: [{ type: "summary_text", text: outcome.thinking }],
    });
  }

  let outputText = "";
  if (outcome.kind === "text") {
    outputText = outcome.text;
    output.push({
      id: `msg_${crypto.randomUUID()}`,
      type: "message",
      status: "completed",
      role: "assistant",
      content: [{ type: "output_text", text: outcome.text, annotations: [] }],
    });
  } else {
    for (const call of outcome.calls) {
      output.push({
        id: `fc_${crypto.randomUUID()}`,
        call_id: call.id,
        type: "function_call",
        name: call.name,
        arguments: call.arguments,
        status: "completed",
      });
    }
  }

  const responseObject = {
    id,
    object: "response",
    created_at: createdAt,
    status: "completed",
    error: null,
    incomplete_details: null,
    instructions: body.instructions ?? null,
    model: modelCheck,
    output,
    output_text: outputText,
    usage: {
      input_tokens: inputTokens,
      output_tokens: outputTokens,
      total_tokens: inputTokens + outputTokens,
      output_tokens_details: { reasoning_tokens: reasoningTokens },
    },
  };

  if (body.stream) {
    // Responses API streams don't end with a "[DONE]" sentinel — the
    // response.completed event followed by stream close is the signal.
    return sseResponse(buildResponsesStreamEvents(responseObject), null);
  }

  return jsonResponse(responseObject);
}

// ---------------------------------------------------------------------------
// Embeddings — POST /v1/embeddings (unchanged: no stdin prompt)
// ---------------------------------------------------------------------------

interface EmbeddingsRequest {
  model: string;
  input: string | string[];
}

// Deterministic pseudo-random vector seeded from the input text — no stdin
// prompt here since typing floating-point vectors by hand isn't practical.
function fakeEmbedding(text: string, dims = 32): number[] {
  let seed = 0;
  for (let i = 0; i < text.length; i++) seed = (seed * 31 + text.charCodeAt(i)) >>> 0;
  const vec: number[] = [];
  for (let i = 0; i < dims; i++) {
    seed = (seed * 1103515245 + 12345) >>> 0;
    vec.push((seed / 0xffffffff) * 2 - 1);
  }
  return vec;
}

async function handleEmbeddings(req: Request): Promise<Response> {
  let body: EmbeddingsRequest;
  try {
    body = (await req.json()) as EmbeddingsRequest;
  } catch {
    return errorResponse("invalid JSON body", 400);
  }
  const modelCheck = requireKnownModel(body.model);
  if (modelCheck instanceof Response) return modelCheck;
  const inputs = Array.isArray(body.input) ? body.input : [body.input];

  return jsonResponse({
    object: "list",
    data: inputs.map((text, index) => ({
      object: "embedding",
      index,
      embedding: fakeEmbedding(String(text)),
    })),
    model: modelCheck,
    usage: {
      prompt_tokens: inputs.reduce((sum, t) => sum + estimateTokens(String(t)), 0),
      total_tokens: inputs.reduce((sum, t) => sum + estimateTokens(String(t)), 0),
    },
  });
}

// ---------------------------------------------------------------------------
// Models — GET /v1/models, GET /v1/models/:id (unchanged)
// ---------------------------------------------------------------------------

function handleModelsList(): Response {
  return jsonResponse({ object: "list", data: MODELS });
}

function handleModelRetrieve(modelId: string): Response {
  const model = MODELS.find((m) => m.id === modelId);
  if (!model) return errorResponse(`The model '${modelId}' does not exist`, 404);
  return jsonResponse(model);
}

// ---------------------------------------------------------------------------
// HTTP server
// ---------------------------------------------------------------------------

const server = Bun.serve({
  port: PORT,
  idleTimeout: 0,
  async fetch(req) {
    const url = new URL(req.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";

    if (req.method === "GET" && path === "/v1/models") return handleModelsList();
    if (req.method === "GET" && path.startsWith("/v1/models/")) {
      return handleModelRetrieve(decodeURIComponent(path.slice("/v1/models/".length)));
    }
    if (req.method === "POST" && path === "/v1/chat/completions") return handleChatCompletions(req);
    if (req.method === "POST" && path === "/v1/completions") return handleCompletions(req);
    if (req.method === "POST" && path === "/v1/responses") return handleResponses(req);
    if (req.method === "POST" && path === "/v1/embeddings") return handleEmbeddings(req);

    if (req.method === "GET" && path === "/") {
      return new Response(PANEL_HTML, { headers: { "content-type": "text/html; charset=utf-8" } });
    }
    if (req.method === "GET" && path === "/panel/events") {
      return new Response(panelEventStream(), {
        headers: { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" },
      });
    }
    if (req.method === "POST" && path.startsWith("/panel/pending/") && path.endsWith("/respond")) {
      const id = decodeURIComponent(path.slice("/panel/pending/".length, -"/respond".length));
      let body: unknown;
      try {
        body = await req.json();
      } catch {
        return jsonResponse({ error: "invalid JSON body" }, 400);
      }
      const err = resolvePending(id, body);
      if (err !== null) return jsonResponse({ error: err }, 400);
      return jsonResponse({ ok: true });
    }

    return errorResponse(`Unknown endpoint: ${req.method} ${path}`, 404, "not_found_error");
  },
});

console.log(`openai-madeup-endpoint listening on http://localhost:${server.port}`);
console.log(`Known models: ${MODELS.map((m) => m.id).join(", ")}`);
console.log(`Operator panel: http://localhost:${server.port}/ — every request waits there for you to answer.\n`);

process.on("SIGINT", () => {
  closePanel();
  process.exit(0);
});
